DiscordToken = "DiscordTokenHere"

EnableBotList = false
BotListToken = "BotListTokenHere"
MongoURL = "mongodb://localhost"

MasterSvr = "HomeServerIDHere"
UserID = "BotUserIDHere"
CacheDir = "/tmp/prototon"

DeveloperIDs = [
    "285937628363227138",
    "459402945792966658"
]