DiscordToken = "DiscordTokenHere"
UserID = "BotUserIDHere"
MasterSvr = "HomeServerIDHere"
GitHubRepoURL = "RepoURLHere"
MongoURL = "mongodb://localhost"
DeveloperIDs = [
    "285937628363227138",
    "459402945792966658"
]

EnableBotList = false
BotListToken = "BotListTokenHere"
CacheDir = "/tmp/prototon"