DiscordToken = "DiscordTokenHere"

EnableBotList = false
BotListToken = "BotListTokenHere"
MongoURL = "mongodb://localhost"

MasterSvr = "HomeServerIDHere"
UserID = "BotUserIDHere"
CacheDir = "/tmp/prototon"