fortunes = [
  "Oh baby, it's certain!",
  "I say it's decidedly so.",
  "Hell yeah, without a doubt!",
  "Yas boo, definitely.",
  "Babu, you may rely on it.",
  "Hmm. As I see it, yes.",
  "Eh, most likely.",
  "I think the outlook for that is good.",
  "Yas, boo.",
  "Well the signs all point to yes. What do you think?",
  "Uhh, reply hazy. Try again.",
  "Try asking again later. PrototonBot is tired. :c",
  "Um. It's better not to tell you now...",
  "I don't think I can predict that right now.",
  "Uh. Concentrate harder and ask again, please.",
  "Don't count on it, boo.",
  "I say no.",
  "Well my bot sources say no, sorry.",
  "Babu, the outlook on that isn't so good...",
  "Sorry, but that's very doubtful."
]

emotions = [
  "Happy! :smile:",
  "Angry! :angry:",
  "Sad. :frowning:",
  "Energized! :stuck_out_tongue_winking_eye:",
  "Motivated. :grin:",
  "Sick. :mask:",
  "In love! :heart_eyes:",
  "Shook! :scream:"
]

series_members = [
  "Akari Hoga",
  "Daiki Isao",
  "Daisuku Hideaki",
  "Fumie Hayashi",
  "Fuzai Tsuisuto",
  "Gehin Kashikoi",
  "Giichi Hokaro",
  "Hibiki Sasiko",
  "Hikari Okami",
  "Hitoshi Yousuke",
  "Kanashi Otokonoko",
  "Marrok Shinu",
  "Nensho Jonetsu",
  "Serhan Serafino",
  "Wulfy Opaugg",
  "Yuka Michiru"
]

rp_members = [
  "Aoi Masaki",
  "Cookie Burns",
  "Daisuke Ozawa",
  "Erriran Ampera",
  "Keanu Lowa",
  "Kiiroi Hikari",
  "Kimura Hidetoshi",
  "Marrok Shinu",
  "Okashito Simmer",
  "Oshaberi Ocha",
  "Paul Maruko",
  "Ruby",
  "Ryuka Takashima",
  "Uyami Anawata",
  "Yui Rio",
  "Yuri Nari",
  "Aisuro Seishinu"
]

all_members = [
  "Aoi Masaki",
  "Cookie Burns",
  "Daisuke Ozawa",
  "Erriran Ampera",
  "Keanu Lowa",
  "Kiiroi Hikari",
  "Kimura Hidetoshi",
  "Marrok Shinu",
  "Okashito Simmer",
  "Oshaberi Ocha",
  "Paul Maruko",
  "Ruby",
  "Ryuka Takashima",
  "Uyami Anawata",
  "Yui Rio",
  "Yuri Nari",
  "Aisuro Seishinu",
  "Akari Hoga",
  "Daiki Isao",
  "Daisuku Hideaki",
  "Fumie Hayashi",
  "Fuzai Tsuisuto",
  "Gehin Kashikoi",
  "Giichi Hokaro",
  "Hibiki Sasiko",
  "Hikari Okami",
  "Hitoshi Yousuke",
  "Kanashi Otokonoko",
  "Marrok Shinu",
  "Nensho Jonetsu",
  "Serhan Serafino",
  "Wulfy Opaugg",
  "Yuka Michiru",
  "Ichiharu Yuuto",
  "Garaxi Nudorosu",
  "Hanamai Wutaba",
  "Haruto Tamagoto",
  "Keitaro Sazama",
  "Candy Chan",
  "Oto Soishi",
  "Cameron Shibanau",
  "Haruka Aozaki",
  "Miko Fuba",
  "Hanko-kun",
  "Wulfy Opaugg",
  "Wulfy Raiden",
  "Heather Hitomi",
  "Hikari Kibo",
  "Kidori Sajimi",
  "Misa Nakano",
  "Miyuki Kiiwu",
  "Shidare Shokubutsu",
  "Skye Aninipot",
  "Rukuta Maruko",
  "Junko Najume",
  "Kokuto Kunitori",
  "Luka Wasabi",
  "Yuriko Akosawa",
  "Marrok Shinuri"
]
