"fortunes" = [
  "Oh baby, it's certain!",
  "I say it's decidedly so.",
  "Hell yeah, without a doubt!",
  "Yas boo, definitely.",
  "Babu, you may rely on it.",
  "Hmm. As I see it, yes.",
  "Eh, most likely.",
  "I think the outlook for that is good.",
  "Yas, boo.",
  "Well the signs all point to yes. What do you think?",
  "Uhh, reply hazy. Try again.",
  "Try asking again later. PrototonBot is tired. :c",
  "Um. It's better not to tell you now...",
  "I don't think I can predict that right now.",
  "Uh. Concentrate harder and ask again, please.",
  "Don't count on it, boo.",
  "I say no.",
  "Well my bot sources say no, sorry.",
  "Babu, the outlook on that isn't so good...",
  "Sorry, but that's very doubtful."
]

"emotions" = [
  "Happy! :smile:",
  "Angry! :angry:",
  "Sad. :frowning:",
  "Energized! :stuck_out_tongue_winking_eye:",
  "Motivated. :grin:",
  "Sick. :mask:",
  "In love! :heart_eyes:",
  "Shook! :scream:",
  "Flustered. :relaxed:",
  "Cool. :sunglasses:",
  "Wanting something.. :pleading_face:",
  "Awkward.. :grimacing:",
  "Tired.. :yawning_face:",
  "Rich, baby! :money_mouth:",
  "Embarrassed. :flushed:",
  "Like partying! :partying_face:",
  "Ponderous.. :thinking:",
  "Annoyed. :rolling_eyes:",
  "LIKE I WANNA BE A COWBOY, BABY! :cowboy:",
  "Gurl, dead- :skull:"
]

"danganronpa_chars" = [
	"Makoto Naegi",
	"Aoi Asahina",
	"Byakuya Togami",
	"Celestia Ludenburg",
	"Chihiro Fujisaki",
	"Hifumi Yamada",
	"Junko Enoshima",
	"Kiyotaka Ishimaru",
	"Kyoko Kirigiri",
	"Leon Kuwata",
	"Mondo Owada",
	"Mukuro Ikusaba",
	"Sakura Ogami",
	"Sayaka Maizono",
	"Toko Fukawa",
	"Yasuhiro Higakure",
	"Hajime Hinata",
	"Akane Owari",
	"Ryota Mitarai",
	"Chiaki Nanami",
	"Fuyuhiko Kuzuryu",
	"Gundham Tanaka",
	"Hiyoko Saionji",
	"Ibuki Mioda",
	"Kazuichi Soda",
	"Mahiru Koizumi",
	"Mikan Tsumiki",
	"Nagito Komaeda",
	"Nekomari Nidai",
	"Peko Pekoyama",
	"Sonia Nevermind",
	"Teruteru Hanamura",
	"Angie Yonaga",
	"Gonta Gokuhara",
	"Himiko Yumeno",
	"K1-B0",
	"Kaito Momota",
	"Kirumi Tojo",
	"Kokichi Oma",
	"Korekiyo Shinguji",
	"Maki Harukawa",
	"Miu Iruma",
	"Rantaro Amami",
	"Ryoma Hoshi",
	"Shuichi Saihara",
	"Tenko Chabashira",
	"Tsumugi Shirogane",
	"Kyosuke Munakata",
	"Seiko Kimura",
	"Koichi Kizakura",
	"Chisa Yukizome",
	"Juzo Sakakura",
	"Miaya Gekkogahara",
	"Ruruka Ando",
	"Sonosuke Izayoi",
	"Daisaku Bandai",
	"Great Gozu"
]